name: Testing Cache Linux -> Windows && Linux -> MacOS

on:
  pull_request:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./test.txt
          key: v1-test-cache

      - name: Create File
        run: |
          touch test.txt
          echo "${{ github.sha }}" > test.txt

      - name: Cat File to be cached
        run: cat test.txt

  windows:
    needs: ["linux"]
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./test.txt
          key: v1-test-cache

      - name: Type File from cache
        run: type test.txt

      - name: Echo github sha for env
        run: echo "${{ github.base_ref }}"

  osx:
    needs: ["linux"]
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ./test.txt
          key: v1-test-cache

      - name: Cat File from cache
        run: cat test.txt

      - name: Echo github sha for env
        run: echo "${{ github.base_ref }}"
